version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_auth
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5431:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net


  mysql:
    image: mysql:8.0
    container_name: mysql_sisbol
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
        - "3305:3306"
    volumes:
        - mysql_data:/var/lib/mysql
    networks:
      - backend_net
  
volumes:
  postgres_data:
  mysql_data:

networks:
  backend_net:
    driver: bridge
    

