app:
  datasource:
    url: jdbc:mysql://localhost:3305/blocksisbol
    username: root
    password: "*s5rv1d0r5$"
    driver-class-name: com.mysql.cj.jdbc.Driver

auth:
  datasource:
    url: jdbc:postgresql://localhost:5431/authdb
    username: root
    password: "*s5rv1d0r5$"
    driver-class-name: org.postgresql.Driver

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
