app:
  datasource:
    url: ${APP_DB_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: ${APP_DB_URL_DRIVER}

auth:
  datasource:
    url: {AUTH_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: ${AUTH_DB_URL_DRIVER}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
