spring.application.name=cadastro.sisbol
# URL do banco de dados (ajuste o nome do banco, host e porta conforme seu ambiente)
spring.datasource.url=jdbc:mysql://localhost:3306/blocksisbol?useSSL=false&serverTimezone=UTC

# Usuário e senha do banco
spring.datasource.username=root
spring.datasource.password=*s5rv1d0r5$

# Driver JDBC do MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Dialeto do Hibernate (usado para geração de queries compatíveis com o MySQL)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Mostra no console as queries geradas pelo Hibernate
spring.jpa.show-sql=true

# Atualização automática do schema (use com cautela)
# create: cria do zero toda vez
# update: atualiza o schema sem apagar dados
# validate: apenas valida o schema existente
# none: não faz nada
spring.jpa.hibernate.ddl-auto=update

# Codificação padrão
spring.datasource.hikari.connection-init-sql=SET NAMES utf8mb4