spring:
  datasource:
    auth:
      url: jdbc:postgresql://localhost:5432/authdb
      username: postgres
      password: senha
    app:
      url: spring.datasource.url=jdbc:mysql://localhost:3306/blocksisbol
      username: root
      password: senha

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
