app:
  datasource:
    url: ${APP_DB_URL}
    username: ${APP_DB_USERNAME}
    password: ${APP_DB_PASSWORD}
    driver-class-name: ${APP_DB_URL}

auth:
  datasource:
    url: ${AUTH_DB_URL}
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}
    driver-class-name: ${AUTH_DB_DRIVER}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
